### ISSUE TITLE
OOM loading properties file

### ISSUE THREAD

**Issue by GrahamBorland** [amplitude/Amplitude-Kotlin#152] opened 2023-10-17 18:35 UTC
## Expected Behavior

No crash

## Current Behavior

Crash trying to allocate 228 MB when reading a properties file

```
java.lang.OutOfMemoryError: Failed to allocate a 228874864 byte allocation with 100663296 free bytes and 124MB until OOM, target footprint 238615760, growth limit 268435456
        at java.util.Properties.loadConvert(Properties.java:546)
        at java.util.Properties.load0(Properties.java:390)
        at java.util.Properties.load(Properties.java:337)
        at com.amplitude.id.utilities.PropertiesFile.load(PropertiesFile.kt:22)
        at com.amplitude.id.FileIdentityStorage.<init>(FileIdentityStorage.kt:23)
        at com.amplitude.id.FileIdentityStorageProvider.getIdentityStorage(FileIdentityStorage.kt:71)
        at com.amplitude.core.Amplitude$build$built$1.invokeSuspend(Amplitude.kt:105)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
```

## Steps to Reproduce
 

Reports captured in Bugsnag from end-users. We have no repro steps. It doesn't seem to be very common (9 instances so far).

## Environment

```
com.amplitude:analytics-android:1.11.1
```
Pixel 6 pro running Android 14

**Comment by justin-fiedler** [comment] 2024-03-04 20:36
Duplicate of #179. 

`v1.16.1` adds error handling to prevent the crash.

**Closed** 2024-03-04 20:37 UTC
